# Makefile for the focaltech touchscreen drivers.

obj-$(CONFIG_TOUCHSCREEN_FT3519T) += focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FT3519T) += focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FT3519T) += focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FT3519T) += focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FT3519T) += focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FT3519T) += focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FT3519T) += focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FT3519T) += focaltech_flash/
obj-$(CONFIG_TOUCHSCREEN_FT3519T) += focaltech_i2c.o
